### ISSUE TITLE
Documentation needs serious style and content review

### ISSUE THREAD

**Issue by sceleri** [LI7XI/AudioAnalyzerDocs#4] opened 2021-05-21 21:31 UTC
Firstly, the FFT Handler is missing a parameter, Granularity. Granularity is only mentioned in one of the examples. The documentation should list all parameters on each handlers main page. Not in some guide explanation.

Then theres the style. It's not a major issue but reading the guides and examples feels like somebody is explaning it to me like I'm 13 and doing html in IT class for the first time. It gets the point across but the style could be improved.

Also, the docs have these chevron/arrow things that indicate if there's subtopics under each topic. They're really bad. The default for topics that contain is "show the expanded chevron but not the subtopics" which leads to me being confused as to which topic actually contains subtopics. Another small issue but still, annoying. Oh and the search results and all other links don't actually scroll to the right position.

I suggest you take a look at Microsofts or Rainmeters documentation, they list all possibe parameters and give a short description of what they do. And their examples don't contain random lines like `MagicNumber=104`. What is that and what does it do. Why is it there.

Love the plugin, it works great but figuring out how to use it is a major roadblock and I'm not surprised why so few skins use it. If you add missing content like the Granularity parameter (and any others that might be missing), I can start rewriting and revising the style of the documentation. Would love to get more people using AudioAnalyzer

**Comment by LI7XI** [comment] 2021-05-24 10:44
Hello @sceleri , sorry for late response, i'm a bit busy nowadays.

First of all, the docs are still WIP, some parameters were removed from the plugin but still exist in the docs. Locally i changed these parameters but still didn't push the commits, because i didn't change all of them yet.

>Then theres the style. It's not a major issue but reading the guides and examples feels like somebody is explaning it to me like I'm 13 and doing html in IT class for the first time. It gets the point across but the style could be improved.

Well, i'm aware of that, i'm planning to do a rewrite of most examples but you can imagen how much time it will take.

>Also, the docs ... the right position.

Actually i didn't really get this part, but some of the things you mentioned here are from docsify itself (what we are using to make the docs).

>I suggest you take a look at Microsofts or Rainmeters documentation, they list all possibe parameters and give a short description of what they do. And their examples don't contain random lines like MagicNumber=104. What is that and what does it do. Why is it there.

\*sigh\*, i'm trying to avoid the clutter, i can't cram all related things in one page, it would be very messy.

Also that parameter(and few other parameters) don't exist anymore, it's only there in the docs, which will be fixed eventually.

>Love the plugin, it works great but figuring out how to use it is a major roadblock and I'm not surprised why so few skins use it.

I know, i'm aware of that, but making good docs isn't an easy task considering how advanced the plugin is. 

Thanks for your feedback!

**Comment by LI7XI** [comment] 2021-05-24 15:26
Btw, i guess in almost every page there is a table of content and a jump list, you can use them for easier navigation.

**Comment by sceleri** [comment] 2021-05-24 16:17
Good to hear that you're working on the docs.

I figured out the scroll thing. When you change pages your scroll is preserved. So if you scroll down on one page and click on another page from the sidebar, you'll be scrolled down the same amount as on the last page. That's the issue. Jump lists work fine, but when you go on a page, you usually dont start from the jump list, you start from where ever you were on the last page.

> i can't cram all related things in one page, it would be very messy.

You absolutely can cram all parameters and their explanations on the related handlers page. That's the point of documentation. Also, if you're worried about being messy, the [fft-example](https://li7xi.github.io/AudioAnalyzerDocs/#/docs/usage-examples/fft-spectrum) has a *full page* paragraph about how CascadeCount works. This information should be on a separate page ([like it is](https://li7xi.github.io/AudioAnalyzerDocs/#/docs/discussions/fft-cascades)), not in the example. 

Examples should provide example code, and briefly explain how it works. The documentation should talk about how and why everything works. Extra information like how Fourier transforms work, should be on separate pages, linked in the documentation. Not in the examples. 

Right now you need to read about 1200+ words to reach the "Parent measure is ready" line in the spectrum example. This needs to change.

**Comment by LI7XI** [comment] 2021-05-24 16:54
>I figured out the scroll ... on the last page.

It's a [known issue](https://github.com/jhildenbiddle/docsify-tabs/issues/8#issuecomment-580074636) and it's bothering me a lot.
~There is [this](https://github.com/rizdaprasetya/docsify-fix-pageload-scroll) plugin which may solve this issue, i'll try it and see if the issue is fixed.~ Unfortunately it didn't work, it's a problem from docsify itself. :(

>Also, if you're worried about being messy, the fft-example has a full page paragraph about how CascadeCount works. This information should be on a separate page (like it is), not in the example.

Well... that page is WIP, and needs a rewrite, but i forgot to hide it from the main branch (i'm working on improving it locally), so what you read there is just an essay i was planning to move it to another page.

P.S Actually not just fft example, but other examples need improving as well, the plan was writing the docs then working on improving it, we improved the first half (everything until discussions), but when it came to usages examples it took me longer than usual because some options changed in the plugin.

So if you saw anything weird it must be written in a transition period (when plugin moved from v1.1.5 to v2), and it will be fixed before the final docs release ^^

As for cramming everything in one place, i don't understand what's the purpose of this, do you have an example of which pages need to be merged together?

>Right now you need to read about 1200+ words to reach the "Parent measure is ready" line in the spectrum example. This needs to change.

I'm working on it, but it will take some time. 

---

Aside from what you mentioned above, do you have any other suggestions? :)

**Comment by sceleri** [comment] 2021-05-25 18:46
Yeah I can live with the scroll now that I figured out what its doing. Still slightly annoying but manageable.

I didn't mean cram everything on one page. I meant cram all relevant information like parameters on the right page. This was mostly a problem because the examples contained parameters that were deleted and I thought that they were missing from the main pages. 

Anyway I think that's the most of my feedback, looking towards to the new and improved guides so I can actually understand what my skin is doing instead of just hoping it works lol

**Comment by LI7XI** [comment] 2021-05-25 19:58
>I didn't mean cram everything on one page. I meant cram all relevant information like parameters on the right page.

You haven't seen handler types subpages?

>This was mostly a problem because the examples contained parameters that were deleted and I thought that they were missing from the main pages.

I know but as i said it took me more time to fix the examples because some parameters changed "after" i wrote the examples. I fixed other pages except the examples which i'm currently working on.

>Anyway I think that's the most of my feedback, looking towards to the new and improved guides so I can actually understand what my skin is doing instead of just hoping it works lol

Btw, there is a separate branch called examples, it's not up to date yet, but you can see for yourself how the skins are made :)

**Comment by LI7XI** [comment] 2021-05-26 19:40
I will close this issue for now, but of course if you have other suggestions you can leave them here ;)

**Closed as completed by LI7XI** 2021-05-26 19:40 UTC

**Comment by LI7XI** [comment] 2021-05-28 23:00
@sceleri I updated fft example, check it out if you are interested.
